[
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "${aws_logs_group}",
          "awslogs-region": "${aws_region_name}",
          "awslogs-stream-prefix": "${aws_logs_stream_prefix}"
        }
      },
      "entryPoint": null,
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": 100,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "906394416424.dkr.ecr.us-east-1.amazonaws.com/aws-for-fluent-bit:latest",
      "startTimeout": null,
      "firelensConfiguration": {
        "type": "fluentbit",
        "options": {
          "enable-ecs-log-metadata": "false",
          "config-file-type": "file",
          "config-file-value": "/fluent-bit/configs/parse-json.conf"
        }
      },
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": "0",
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "log_router_sumo"
    },
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awsfirelens",
        "secretOptions": null,
        "options": {
          "tls.verify": "off",
          "Format": "json_lines",
          "Header": "X-Sumo-Category ${environment}-${ecs_service_name}",
          "Port": "443",
          "Host": "endpoint1.collection.us2.sumologic.com",
          "tls": "on",
          "URI": "/receiver/v1/http/ZaVnC4dhaV3iF49y7yCzPnRmocMMg_qV0e7HKRCnUo0Ax9uRoyQVxl9CYD029cnHTg_IH1jWG3qt2g9_SgkR3pYmBsaSJvyrPNMKnFFFS9PiPgxROWNn3g==",
          "Name": "http"
        }
      },
      "entryPoint": null,
      "portMappings": ${port_mappings},
      "command": null,
      "linuxParameters": {
        "initProcessEnabled": true
      },
      "cpu": 0,
      "environment": ${task_env_vars},
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": ${task_memory_max},
      "memoryReservation": ${task_memory_min},
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "${app_docker_image_tag}",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "app"
    }
  ]
